clusterName: {{ cookiecutter.cluster }}
splunkObservability:
  realm: {{ cookiecutter.realm }}
  accessToken: {{ cookiecutter.token }}

otelAgent:
  config:
    receivers:
      smartagent/redis:    
        type: collectd/redis
        host: redis
        port: 6379
    service:
      pipelines:
        metrics:
          receivers:
            - hostmetrics
            - kubeletstats
            - receiver_creator
            - signalfx
            - smartagent/redis