clusterName: {{ cookiecutter.cluster }}
splunkObservability.realm: {{cookiecutter.realm}}
splunkObservability.accessToken: {{ cookiecutter.token }}

fluentd:
  config:
    containers:
      logFormatType: cri
      criTimeFormat: "%Y-%m-%dT%H:%M:%S.%NZ"